/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as LearnCourseSlugRouteImport } from './routes/learn/$courseSlug'
import { Route as InstructorDashboardRouteImport } from './routes/instructor/dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBadgesRouteImport } from './routes/admin/badges'
import { Route as PublicVerifyCertificateRouteImport } from './routes/_public/verify-certificate'
import { Route as PublicLeaderboardRouteImport } from './routes/_public/leaderboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMyLearningRouteImport } from './routes/_app/my-learning'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCertificatesRouteImport } from './routes/_app/certificates'
import { Route as AppBadgesRouteImport } from './routes/_app/badges'
import { Route as InstructorCoursesIndexRouteImport } from './routes/instructor/courses/index'
import { Route as PublicCoursesIndexRouteImport } from './routes/_public/courses/index'
import { Route as LearnCourseSlugLessonIdRouteImport } from './routes/learn/$courseSlug/$lessonId'
import { Route as InstructorCoursesNewRouteImport } from './routes/instructor/courses/new'
import { Route as InstructorCoursesCourseIdRouteImport } from './routes/instructor/courses/$courseId'
import { Route as PublicCoursesCourseSlugRouteImport } from './routes/_public/courses/$courseSlug'
import { Route as InstructorCoursesCourseIdEditRouteImport } from './routes/instructor/courses/$courseId/edit'
import { Route as InstructorCoursesCourseIdCurriculumRouteImport } from './routes/instructor/courses/$courseId/curriculum'
import { Route as InstructorCoursesCourseIdLessonsLessonIdRouteImport } from './routes/instructor/courses/$courseId/lessons/$lessonId'

const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const LearnCourseSlugRoute = LearnCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => LearnRoute,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstructorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AdminRoute,
} as any)
const PublicVerifyCertificateRoute = PublicVerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLeaderboardRoute = PublicLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PublicRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMyLearningRoute = AppMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppBadgesRoute = AppBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AppRoute,
} as any)
const InstructorCoursesIndexRoute = InstructorCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => InstructorRoute,
} as any)
const PublicCoursesIndexRoute = PublicCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => PublicRoute,
} as any)
const LearnCourseSlugLessonIdRoute = LearnCourseSlugLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LearnCourseSlugRoute,
} as any)
const InstructorCoursesNewRoute = InstructorCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorCoursesCourseIdRoute =
  InstructorCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => InstructorRoute,
  } as any)
const PublicCoursesCourseSlugRoute = PublicCoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => PublicRoute,
} as any)
const InstructorCoursesCourseIdEditRoute =
  InstructorCoursesCourseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => InstructorCoursesCourseIdRoute,
  } as any)
const InstructorCoursesCourseIdCurriculumRoute =
  InstructorCoursesCourseIdCurriculumRouteImport.update({
    id: '/curriculum',
    path: '/curriculum',
    getParentRoute: () => InstructorCoursesCourseIdRoute,
  } as any)
const InstructorCoursesCourseIdLessonsLessonIdRoute =
  InstructorCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => InstructorCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/badges': typeof AppBadgesRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/favorites': typeof AppFavoritesRoute
  '/my-learning': typeof AppMyLearningRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/leaderboard': typeof PublicLeaderboardRoute
  '/verify-certificate': typeof PublicVerifyCertificateRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/learn/$courseSlug': typeof LearnCourseSlugRouteWithChildren
  '/': typeof PublicIndexRoute
  '/courses/$courseSlug': typeof PublicCoursesCourseSlugRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRouteWithChildren
  '/instructor/courses/new': typeof InstructorCoursesNewRoute
  '/learn/$courseSlug/$lessonId': typeof LearnCourseSlugLessonIdRoute
  '/courses': typeof PublicCoursesIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/instructor/courses/$courseId/curriculum': typeof InstructorCoursesCourseIdCurriculumRoute
  '/instructor/courses/$courseId/edit': typeof InstructorCoursesCourseIdEditRoute
  '/instructor/courses/$courseId/lessons/$lessonId': typeof InstructorCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/badges': typeof AppBadgesRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/favorites': typeof AppFavoritesRoute
  '/my-learning': typeof AppMyLearningRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/leaderboard': typeof PublicLeaderboardRoute
  '/verify-certificate': typeof PublicVerifyCertificateRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/learn/$courseSlug': typeof LearnCourseSlugRouteWithChildren
  '/': typeof PublicIndexRoute
  '/courses/$courseSlug': typeof PublicCoursesCourseSlugRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRouteWithChildren
  '/instructor/courses/new': typeof InstructorCoursesNewRoute
  '/learn/$courseSlug/$lessonId': typeof LearnCourseSlugLessonIdRoute
  '/courses': typeof PublicCoursesIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/instructor/courses/$courseId/curriculum': typeof InstructorCoursesCourseIdCurriculumRoute
  '/instructor/courses/$courseId/edit': typeof InstructorCoursesCourseIdEditRoute
  '/instructor/courses/$courseId/lessons/$lessonId': typeof InstructorCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/_app/badges': typeof AppBadgesRoute
  '/_app/certificates': typeof AppCertificatesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/my-learning': typeof AppMyLearningRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_public/leaderboard': typeof PublicLeaderboardRoute
  '/_public/verify-certificate': typeof PublicVerifyCertificateRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/learn/$courseSlug': typeof LearnCourseSlugRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_public/courses/$courseSlug': typeof PublicCoursesCourseSlugRoute
  '/instructor/courses/$courseId': typeof InstructorCoursesCourseIdRouteWithChildren
  '/instructor/courses/new': typeof InstructorCoursesNewRoute
  '/learn/$courseSlug/$lessonId': typeof LearnCourseSlugLessonIdRoute
  '/_public/courses/': typeof PublicCoursesIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/instructor/courses/$courseId/curriculum': typeof InstructorCoursesCourseIdCurriculumRoute
  '/instructor/courses/$courseId/edit': typeof InstructorCoursesCourseIdEditRoute
  '/instructor/courses/$courseId/lessons/$lessonId': typeof InstructorCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/instructor'
    | '/learn'
    | '/badges'
    | '/certificates'
    | '/dashboard'
    | '/favorites'
    | '/my-learning'
    | '/profile'
    | '/settings'
    | '/login'
    | '/register'
    | '/leaderboard'
    | '/verify-certificate'
    | '/admin/badges'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/users'
    | '/instructor/dashboard'
    | '/learn/$courseSlug'
    | '/'
    | '/courses/$courseSlug'
    | '/instructor/courses/$courseId'
    | '/instructor/courses/new'
    | '/learn/$courseSlug/$lessonId'
    | '/courses'
    | '/instructor/courses'
    | '/instructor/courses/$courseId/curriculum'
    | '/instructor/courses/$courseId/edit'
    | '/instructor/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/instructor'
    | '/learn'
    | '/badges'
    | '/certificates'
    | '/dashboard'
    | '/favorites'
    | '/my-learning'
    | '/profile'
    | '/settings'
    | '/login'
    | '/register'
    | '/leaderboard'
    | '/verify-certificate'
    | '/admin/badges'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/users'
    | '/instructor/dashboard'
    | '/learn/$courseSlug'
    | '/'
    | '/courses/$courseSlug'
    | '/instructor/courses/$courseId'
    | '/instructor/courses/new'
    | '/learn/$courseSlug/$lessonId'
    | '/courses'
    | '/instructor/courses'
    | '/instructor/courses/$courseId/curriculum'
    | '/instructor/courses/$courseId/edit'
    | '/instructor/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_public'
    | '/admin'
    | '/instructor'
    | '/learn'
    | '/_app/badges'
    | '/_app/certificates'
    | '/_app/dashboard'
    | '/_app/favorites'
    | '/_app/my-learning'
    | '/_app/profile'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/register'
    | '/_public/leaderboard'
    | '/_public/verify-certificate'
    | '/admin/badges'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/users'
    | '/instructor/dashboard'
    | '/learn/$courseSlug'
    | '/_public/'
    | '/_public/courses/$courseSlug'
    | '/instructor/courses/$courseId'
    | '/instructor/courses/new'
    | '/learn/$courseSlug/$lessonId'
    | '/_public/courses/'
    | '/instructor/courses/'
    | '/instructor/courses/$courseId/curriculum'
    | '/instructor/courses/$courseId/edit'
    | '/instructor/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/learn/$courseSlug': {
      id: '/learn/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/learn/$courseSlug'
      preLoaderRoute: typeof LearnCourseSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/badges': {
      id: '/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/verify-certificate': {
      id: '/_public/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof PublicVerifyCertificateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/leaderboard': {
      id: '/_public/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof PublicLeaderboardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-learning': {
      id: '/_app/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof AppMyLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates': {
      id: '/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/badges': {
      id: '/_app/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AppBadgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/instructor/courses/': {
      id: '/instructor/courses/'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorCoursesIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_public/courses/': {
      id: '/_public/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/learn/$courseSlug/$lessonId': {
      id: '/learn/$courseSlug/$lessonId'
      path: '/$lessonId'
      fullPath: '/learn/$courseSlug/$lessonId'
      preLoaderRoute: typeof LearnCourseSlugLessonIdRouteImport
      parentRoute: typeof LearnCourseSlugRoute
    }
    '/instructor/courses/new': {
      id: '/instructor/courses/new'
      path: '/courses/new'
      fullPath: '/instructor/courses/new'
      preLoaderRoute: typeof InstructorCoursesNewRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/courses/$courseId': {
      id: '/instructor/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/instructor/courses/$courseId'
      preLoaderRoute: typeof InstructorCoursesCourseIdRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/_public/courses/$courseSlug': {
      id: '/_public/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof PublicCoursesCourseSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/instructor/courses/$courseId/edit': {
      id: '/instructor/courses/$courseId/edit'
      path: '/edit'
      fullPath: '/instructor/courses/$courseId/edit'
      preLoaderRoute: typeof InstructorCoursesCourseIdEditRouteImport
      parentRoute: typeof InstructorCoursesCourseIdRoute
    }
    '/instructor/courses/$courseId/curriculum': {
      id: '/instructor/courses/$courseId/curriculum'
      path: '/curriculum'
      fullPath: '/instructor/courses/$courseId/curriculum'
      preLoaderRoute: typeof InstructorCoursesCourseIdCurriculumRouteImport
      parentRoute: typeof InstructorCoursesCourseIdRoute
    }
    '/instructor/courses/$courseId/lessons/$lessonId': {
      id: '/instructor/courses/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/instructor/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof InstructorCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof InstructorCoursesCourseIdRoute
    }
  }
}

interface AppRouteChildren {
  AppBadgesRoute: typeof AppBadgesRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppMyLearningRoute: typeof AppMyLearningRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBadgesRoute: AppBadgesRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppMyLearningRoute: AppMyLearningRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLeaderboardRoute: typeof PublicLeaderboardRoute
  PublicVerifyCertificateRoute: typeof PublicVerifyCertificateRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCoursesCourseSlugRoute: typeof PublicCoursesCourseSlugRoute
  PublicCoursesIndexRoute: typeof PublicCoursesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLeaderboardRoute: PublicLeaderboardRoute,
  PublicVerifyCertificateRoute: PublicVerifyCertificateRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCoursesCourseSlugRoute: PublicCoursesCourseSlugRoute,
  PublicCoursesIndexRoute: PublicCoursesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBadgesRoute: AdminBadgesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InstructorCoursesCourseIdRouteChildren {
  InstructorCoursesCourseIdCurriculumRoute: typeof InstructorCoursesCourseIdCurriculumRoute
  InstructorCoursesCourseIdEditRoute: typeof InstructorCoursesCourseIdEditRoute
  InstructorCoursesCourseIdLessonsLessonIdRoute: typeof InstructorCoursesCourseIdLessonsLessonIdRoute
}

const InstructorCoursesCourseIdRouteChildren: InstructorCoursesCourseIdRouteChildren =
  {
    InstructorCoursesCourseIdCurriculumRoute:
      InstructorCoursesCourseIdCurriculumRoute,
    InstructorCoursesCourseIdEditRoute: InstructorCoursesCourseIdEditRoute,
    InstructorCoursesCourseIdLessonsLessonIdRoute:
      InstructorCoursesCourseIdLessonsLessonIdRoute,
  }

const InstructorCoursesCourseIdRouteWithChildren =
  InstructorCoursesCourseIdRoute._addFileChildren(
    InstructorCoursesCourseIdRouteChildren,
  )

interface InstructorRouteChildren {
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorCoursesCourseIdRoute: typeof InstructorCoursesCourseIdRouteWithChildren
  InstructorCoursesNewRoute: typeof InstructorCoursesNewRoute
  InstructorCoursesIndexRoute: typeof InstructorCoursesIndexRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorCoursesCourseIdRoute: InstructorCoursesCourseIdRouteWithChildren,
  InstructorCoursesNewRoute: InstructorCoursesNewRoute,
  InstructorCoursesIndexRoute: InstructorCoursesIndexRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

interface LearnCourseSlugRouteChildren {
  LearnCourseSlugLessonIdRoute: typeof LearnCourseSlugLessonIdRoute
}

const LearnCourseSlugRouteChildren: LearnCourseSlugRouteChildren = {
  LearnCourseSlugLessonIdRoute: LearnCourseSlugLessonIdRoute,
}

const LearnCourseSlugRouteWithChildren = LearnCourseSlugRoute._addFileChildren(
  LearnCourseSlugRouteChildren,
)

interface LearnRouteChildren {
  LearnCourseSlugRoute: typeof LearnCourseSlugRouteWithChildren
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnCourseSlugRoute: LearnCourseSlugRouteWithChildren,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
